name: Run Auto Build

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopen]
    branches:
      - main

jobs:

  date:
    runs-on: ubuntu-20.04
    outputs:
      current_date: ${{ steps.get_date.outputs.now }}
    steps:
      - id: get_date
        run: echo "now"

  job_one:
    runs-on: ubuntu-20.04
    needs: date
    steps: 
      - uses: actions/checkout@v3
      - name: job one
        run: exit 1

  job_two:
    runs-on: ubuntu-20.04
    needs: date
    steps:
      - uses: actions/checkout@v3
      - name: job two
        run: exit 0
          #con
  job_three:
    runs-on: ubuntu-20.04
    needs: [job_one, job_two]
    if: always()
    steps:
      - name: job three failure check
        run: | 
          if [[ needs.job_one.result == 'failure' || needs.job_two.result == 'failure' ]]; then
            echo "job one or two failed"
            exit 1
          else 
            echo $job_one_result
            echo $job_two_result
            echo "no issues"
            exit 0
          fi

        

      
